<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>smart-box</AssemblyName>
    <RootNamespace>SingBoxSmart.Windows</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>0.1.0</Version>
    <InformationalVersion>smart-box 0.1.0 (core 1.14.0-beta.14)</InformationalVersion>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <DebugType>none</DebugType>
  </PropertyGroup>
</Project>
